### PR TITLE
Fix/configure default lint for fe-ionic 573 - master

### LINKED ISSUE #573: current fe-ionic provision broken as of 17 April 2021
**Describe the bug**
Last ODS test run failed at `fe-ionic` provisioning step. It looks like it is due to `fe-ionic` not being able to locate `tslint.json`

**To Reproduce**
1. Provision `fe-ionic` or check latest test logs in `ods-core` tests [reports](https://github.com/opendevstack/ods-core#current-master-ami-build-log)
2. Stage `init ionic project` fails

**Expected behavior**
The `init.sh` script should work

**Affected version (please complete the following information):**
 - OpenShift: 3.11, 4
 - OpenDevStack 3.x, master

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
[0;32m    amazon-ebs: [Initialize output directory-fe-ionic-test] **** STARTING stage 'Initialize output directory' for component 'fe-ionic-test' branch 'master' ****[0m
[0;32m    amazon-ebs: [Pipeline] stage[0m
[0;32m    amazon-ebs: [Pipeline] { (Initialize output directory)[0m
[0;32m    amazon-ebs: [Pipeline] fileExists[0m
[0;32m    amazon-ebs: [Pipeline] sh[0m
[0;32m    amazon-ebs: WARNING: Unknown parameter(s) found for class type 'org.jenkinsci.plugins.workflow.steps.durable_task.ShellStep': label[0m
[0;32m    amazon-ebs: + mkdir -p fe-ionic-test[0m
[0;32m    amazon-ebs: [Pipeline] }[0m
[0;32m    amazon-ebs: [Pipeline] // stage[0m
[0;32m    amazon-ebs: [Pipeline] echo[0m
[0;32m    amazon-ebs: [Initialize output directory-fe-ionic-test] **** ENDED stage 'Initialize output directory' for component 'fe-ionic-test' branch 'master' **** (took 501 ms)[0m
[0;32m    amazon-ebs: [Pipeline] stage[0m
[0;32m    amazon-ebs: [Pipeline] { (update ionic cli)[0m
[0;32m    amazon-ebs: [Pipeline] sh[0m
[0;32m    amazon-ebs: + npm install -g ionic@5.4.16[0m
[0;32m    amazon-ebs: npm WARN deprecated ionic@5.4.16: The Ionic CLI now uses ✨ @ionic/cli ✨ for its package name! 👉 https://twitter.com/ionicframework/status/1223268498362851330[0m
[0;32m    amazon-ebs: /home/jenkins/.npm-global/bin/ionic -> /home/jenkins/.npm-global/lib/node_modules/ionic/bin/ionic[0m
[0;32m    amazon-ebs: + ionic@5.4.16[0m
[0;32m    amazon-ebs: added 233 packages from 154 contributors in 25.455s[0m
[0;32m    amazon-ebs: + ionic version[0m
[0;32m    amazon-ebs: 5.4.16[0m
[0;32m    amazon-ebs: [Pipeline] }[0m
[0;32m    amazon-ebs: [Pipeline] // stage[0m
[0;32m    amazon-ebs: [Pipeline] stage[0m
[0;32m    amazon-ebs: [Pipeline] { (init ionic project)[0m
[0;32m    amazon-ebs: [Pipeline] sh[0m
[0;32m    amazon-ebs: + sh fe-ionic/init.sh --project unitt --component fe-ionic-test --group null[0m
[0;32m    amazon-ebs: +++ dirname fe-ionic/init.sh[0m
[0;32m    amazon-ebs: ++ cd fe-ionic[0m
[0;32m    amazon-ebs: ++ pwd[0m
[0;32m    amazon-ebs: + SCRIPT_DIR=/tmp/workspace/unitt-cd/unitt-cd-prov-fe-ionic-opendevstack-master/fe-ionic[0m
[0;32m    amazon-ebs: + [[ 6 > 0 ]][0m
[0;32m    amazon-ebs: + case $1 in[0m
[0;32m    amazon-ebs: + PROJECT=unitt[0m
[0;32m    amazon-ebs: + shift[0m
[0;32m    amazon-ebs: + shift[0m
[0;32m    amazon-ebs: + [[ 4 > 0 ]][0m
[0;32m    amazon-ebs: + case $1 in[0m
[0;32m    amazon-ebs: + COMPONENT=fe-ionic-test[0m
[0;32m    amazon-ebs: + shift[0m
[0;32m    amazon-ebs: + shift[0m
[0;32m    amazon-ebs: + [[ 2 > 0 ]][0m
[0;32m    amazon-ebs: + case $1 in[0m
[0;32m    amazon-ebs: + GROUP=null[0m
[0;32m    amazon-ebs: + shift[0m
[0;32m    amazon-ebs: + shift[0m
[0;32m    amazon-ebs: + [[ 0 > 0 ]][0m
[0;32m    amazon-ebs: + echo 'generate project'[0m
[0;32m    amazon-ebs: generate project[0m
[0;32m    amazon-ebs: + mkdir start_fe-ionic-test[0m
[0;32m    amazon-ebs: + cd start_fe-ionic-test[0m
[0;32m    amazon-ebs: + ionic start fe-ionic-test blank --type=angular --no-deps --no-git --no-interactive[0m
[0;32m    amazon-ebs: [INFO] Existing git project found (/tmp/workspace/unitt-cd/unitt-cd-prov-fe-ionic-opendevstack-master). Git operations are disabled.[0m
[0;32m    amazon-ebs: ✔ Preparing directory ./fe-ionic-test - done![0m
[0;32m    amazon-ebs: ✔ Downloading and extracting blank starter - done![0m
[0;32m    amazon-ebs:[0m
[0;32m    amazon-ebs:[0m
[0;32m    amazon-ebs: [INFO] Next Steps:[0m
[0;32m    amazon-ebs:[0m
[0;32m    amazon-ebs:        - Go to your newly created project: cd ./fe-ionic-test[0m
[0;32m    amazon-ebs:        - Run ionic serve within the app directory to see your app[0m
[0;32m    amazon-ebs:        - Build features and components: https://ion.link/scaffolding-docs[0m
[0;32m    amazon-ebs:        - Run your app on a hardware or virtual device: https://ion.link/running-docs[0m
[0;32m    amazon-ebs: + mv fe-ionic-test/ ..[0m
[0;32m    amazon-ebs: + cd ../fe-ionic-test[0m
[0;32m    amazon-ebs: + rm -r ../start_fe-ionic-test[0m
[0;32m    amazon-ebs: + echo 'Change test setup to single run in karma.conf.js'[0m
[0;32m    amazon-ebs: Change test setup to single run in karma.conf.js[0m
[0;32m    amazon-ebs: + sed -i 's|\s*singleRun: false|singleRun: true|' ./karma.conf.js[0m
[0;32m    amazon-ebs: + echo 'Configure headless chrome in karma.conf.js'[0m
[0;32m    amazon-ebs: Configure headless chrome in karma.conf.js[0m
[0;32m    amazon-ebs: + read -r -d '' CHROME_CONFIG[0m
[0;32m    amazon-ebs: + true[0m
[0;32m    amazon-ebs: + sed -i 's|\s*browsers: \['\''Chrome'\''\],|browsers: \['\''ChromeNoSandboxHeadless'\''\],\[0m
[0;32m    amazon-ebs:     customLaunchers: {\[0m
[0;32m    amazon-ebs:       ChromeNoSandboxHeadless: {\[0m
[0;32m    amazon-ebs:         base: '\''Chrome'\'',\[0m
[0;32m    amazon-ebs:         flags: \[\[0m
[0;32m    amazon-ebs:           '\''--no-sandbox'\'',\[0m
[0;32m    amazon-ebs:           // See https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md\[0m
[0;32m    amazon-ebs:           '\''--headless'\'',\[0m
[0;32m    amazon-ebs:           '\''--disable-gpu'\'',\[0m
[0;32m    amazon-ebs:           // Without a remote debugging port, Google Chrome exits immediately.\[0m
[0;32m    amazon-ebs:           '\'' --remote-debugging-port=9222'\'',\[0m
[0;32m    amazon-ebs:         \],\[0m
[0;32m    amazon-ebs:       },\[0m
[0;32m    amazon-ebs:     },|' ./karma.conf.js[0m
[0;32m    amazon-ebs: + sed -i 's|\(browsers:\)|    \1|g' ./karma.conf.js[0m
[0;32m    amazon-ebs: + echo 'Add required plugins in karma.conf.js'[0m
[0;32m    amazon-ebs: Add required plugins in karma.conf.js[0m
[0;32m    amazon-ebs: + sed -i '/plugins: \[/a\     \ require('\''karma-junit-reporter'\''),' ./karma.conf.js[0m
[0;32m    amazon-ebs: + echo 'Configure junit xml reporter in karma.conf.js'[0m
[0;32m    amazon-ebs: Configure junit xml reporter in karma.conf.js[0m
[0;32m    amazon-ebs: + read -r -d '' UNIT_XML_CONFIG[0m
[0;32m    amazon-ebs: + true[0m
[0;32m    amazon-ebs: + sed -i 's|\s*reporters: \['\''progress'\'', '\''kjhtml'\''\],|reporters: \['\''progress'\'', '\''junit'\'', '\''kjhtml'\''\],\[0m
[0;32m    amazon-ebs: \[0m
[0;32m    amazon-ebs:     junitReporter: {\[0m
[0;32m    amazon-ebs:       outputDir: '\''./build/test-results/test'\'',\[0m
[0;32m    amazon-ebs:       outputFile: '\''test-results.xml'\'',\[0m
[0;32m    amazon-ebs:       useBrowserName: false\[0m
[0;32m    amazon-ebs:     },|' ./karma.conf.js[0m
[0;32m    amazon-ebs: + echo 'Fix path for coverage analysis output'[0m
[0;32m    amazon-ebs: Fix path for coverage analysis output[0m
[0;32m    amazon-ebs: + sed -i 's|\s*__dirname, '\''\.\./coverage'\''|__dirname, '\''coverage'\''|' ./karma.conf.js[0m
[0;32m    amazon-ebs: + echo 'Adjust package.json to have the full test'[0m
[0;32m    amazon-ebs: Adjust package.json to have the full test[0m
[0;32m    amazon-ebs: + sed -i 's|\s*"test": "ng test"|"test": "ng test --code-coverage --reporters=junit --progress=false"|' ./package.json[0m
[0;32m    amazon-ebs: + sed -i 's|\s*"devDependencies": {|"devDependencies": { "karma-junit-reporter": "^2.0.1",|' ./package.json[0m
[0;32m    amazon-ebs: + echo 'Fix linting rules to run with generated tests'[0m
[0;32m    amazon-ebs: Fix linting rules to run with generated tests[0m
[0;32m    amazon-ebs: + sed -i 's|\s*"rules": {|"rules": { "one-variable-per-declaration": false,|' ./tslint.json[0m
[0;32m    amazon-ebs: sed: can't read ./tslint.json: No such file or directory[0m
[0;32m    amazon-ebs: [Pipeline] }[0m
[0;32m    amazon-ebs: [Pipeline] // stage[0m
[0;32m    amazon-ebs: [Pipeline] }[0m
[0;32m    amazon-ebs: [Pipeline] // node[0m
[0;32m    amazon-ebs: [Pipeline] }[0m
[0;32m    amazon-ebs: [Pipeline] // podTemplate[0m
[0;32m    amazon-ebs: [Pipeline] End of Pipeline[0m
[0;32m    amazon-ebs: ERROR: script returned exit code 2[0m
[0;32m    amazon-ebs: Finished: ionicFAILURE[0m
[0;32m    amazon-ebs: provision pipeline run for fe-ionic-test returned:[0m
[0;32m    amazon-ebs: [[0m
[0;32m    amazon-ebs:   {[0m
[0;32m    amazon-ebs:     "stage": "Checkout quickstarter",[0m
[0;32m    amazon-ebs:     "status": "SUCCESS"[0m
[0;32m    amazon-ebs:   },[0m
[0;32m    amazon-ebs:   {[0m
[0;32m    amazon-ebs:     "stage": "Initialize output directory",[0m
[0;32m    amazon-ebs:     "status": "SUCCESS"[0m
[0;32m    amazon-ebs:   },[0m
[0;32m    amazon-ebs:   {[0m
[0;32m    amazon-ebs:     "stage": "update ionic cli",[0m
[0;32m    amazon-ebs:     "status": "SUCCESS"[0m
[0;32m    amazon-ebs:   },[0m
[0;32m    amazon-ebs:   {[0m
[0;32m    amazon-ebs:     "stage": "init ionic project",[0m
[0;32m    amazon-ebs:     "status": "FAILED"[0m
[0;32m    amazon-ebs:   }[0m
[0;32m    amazon-ebs: ][0m
[0;32m    amazon-ebs:     quickstarter_test.go:288: Jenkins stages mismatch (-want +got):[0m
[0;32m    amazon-ebs:           ([0m
[0;32m    amazon-ebs:           	"""[0m
[0;32m    amazon-ebs:           	... // 13 identical lines[0m
[0;32m    amazon-ebs:           	  {[0m
[0;32m    amazon-ebs:           	    "stage": "init ionic project",[0m
[0;32m    amazon-ebs:         - 	    "status": "SUCCESS"[0m
[0;32m    amazon-ebs:         - 	  },[0m
[0;32m    amazon-ebs:         - 	  {[0m
[0;32m    amazon-ebs:         - 	    "stage": "Create OpenShift resources",[0m
[0;32m    amazon-ebs:         - 	    "status": "SUCCESS"[0m
[0;32m    amazon-ebs:         - 	  },[0m
[0;32m    amazon-ebs:         - 	  {[0m
[0;32m    amazon-ebs:         - 	    "stage": "Create Jenkinsfile",[0m
[0;32m    amazon-ebs:         - 	    "status": "SUCCESS"[0m
[0;32m    amazon-ebs:         - 	  },[0m
[0;32m    amazon-ebs:         - 	  {[0m
[0;32m    amazon-ebs:         - 	    "stage": "Create sonar-project.properties",[0m
[0;32m    amazon-ebs:         - 	    "status": "SUCCESS"[0m
[0;32m    amazon-ebs:         - 	  },[0m
[0;32m    amazon-ebs:         - 	  {[0m
[0;32m    amazon-ebs:         - 	    "stage": "Push to remote",[0m
[0;32m    amazon-ebs:         - 	    "status": "SUCCESS"[0m
[0;32m    amazon-ebs:         + 	    "status": "FAILED"[0m
[0;32m    amazon-ebs:           	  }[0m
[0;32m    amazon-ebs:           	][0m
[0;32m    amazon-ebs:           	"""[0m
[0;32m    amazon-ebs:           )[0m
[0;32m    amazon-ebs:[0m
```

**Additional context**
We could take the chance to doing some housekeeping with the `fe-ionic` CLI and related dependencies

### PR DESCRIPTION
**Pull request by bljubisic**
Adding default linter for Ionic. Now it is eslint as tslint is deprecated.

Closes #573 
Fixes #573

### CODE REVIEW

**Review by cschweikert — APPROVED** [review]

File: fe-ionic/Jenkinsfile [hunk 1]
```diff
@@ -22,6 +22,7 @@ odsQuickstarterPipeline(
 
   stage("update ionic cli") {
     sh "npm install -g ionic@${ionicVersion} && ionic version"
+    sh "npm install -g eslint && eslint -v"
```
Comment (michaelsauter) [inline fe-ionic/Jenkinsfile:25]: I think lately we have tried to pin the version to avoid running into issues sometime after the quickstarter installation. Maybe we can do that for `eslint` as well?

That said, `ionic@${ionicVersion}` apparently hasn't had the desired effect since now things broke. Can we double check why this is happening?

Comment (bljubisic) [reply fe-ionic/Jenkinsfile:25]: I will try to find when did they removed the tslint from the configuration. Also, I will add the eslint version tag in the PR.

File: fe-ionic/init.sh [hunk 2]
```diff
@@ -77,13 +77,14 @@ echo "Adjust package.json to have the full test"
...
 echo "fix nexus repo path"
 repo_path=$(echo "$GROUP" | tr . /)
 sed -i.bak "s|org/opendevstack/projectId|$repo_path|g" $SCRIPT_DIR/files/docker/Dockerfile
 rm $SCRIPT_DIR/files/docker/Dockerfile.bak
 
 echo "copy files from quickstart to generated project"
 cp -rv $SCRIPT_DIR/files/. .
+
+echo "configure eslint"
+npm install @typescript-eslint/eslint-plugin@latest --save-dev
```
Comment (clemensutschig) [inline fe-ionic/init.sh:89]: same here-  can we please pin versions

File: fe-ionic/Jenkinsfile (hunk 1 above)
Comment (bljubisic) [reply fe-ionic/Jenkinsfile]: Ionic in version 5 has removed tslint as a default linter option. It starts without any linter so the user can choose which one will they use. Ours worked because we had tslint added in package.json, and it was all ok until the line in init.sh that actually changes tslint.json was added. This change triggered the bug. I have removed that line as it is not needed in eslint and I have added eslint as a default option for linter.

**Review by clemensutschig — APPROVED** [review]

**Comment by clemensutschig** [comment]
@bljubisic  - you broke master ... see latest build logs ...

```
Error: Failed to load plugin '@typescript-eslint' declared in '--config': Cannot find module 'eslint'[0m
[0;32m    amazon-ebs: Require stack:[0m
[0;32m    amazon-ebs: - /tmp/workspace/unitt-cd/unitt-cd-prov-fe-ionic-opendevstack-master/fe-ionic-test/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/CLIEngine.js[0m
[0;32m    amazon-ebs: - /tmp/workspace/unitt-cd/unitt-cd-prov-fe-ionic-opendevstack-master/fe-ionic-test/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/index.js[0m
[0;32m    amazon-ebs: - /tmp/workspace/unitt-cd/unitt-cd-prov-fe-ionic-opendevstack-master/fe-ionic-test/node_modules/@typescript-eslint/experimental-utils/dist/eslint-utils/RuleTester.js[0m
[0;32m    amazon-ebs: - /tmp/workspace/unitt-cd/unitt-cd-prov-fe-ionic-opendevstack-master/fe-ionic-test/node_modules/@typescript-eslint/experimental-utils/dist/eslint-utils/index.js[0m
[0;32m    amazon-ebs: - /tmp/workspace/unitt-cd/unitt-cd-prov-fe-ionic-opendevstack-master/fe-ionic-test/node_modules/@typescript-eslint/experimental-utils/dist/index.js[0m
[0;32m    amazon-ebs: - /tmp/workspace/unitt-cd/unitt-cd-prov-fe-ionic-opendevstack-master/fe-ionic-test/node_modules/@typescript-eslint/eslint-plugin/dist/rules/adjacent-overload-signatures.js[0m
[0;32m    amazon-ebs: - /tmp/workspace/unitt-cd/unitt-cd-prov-fe-ionic-opendevstack-master/fe-ionic-test/node_modules/@typescript-eslint/eslint-plugin/dist/rules/index.js[0m
[0;32m    amazon-ebs: - /tmp/workspace/unitt-cd/unitt-cd-prov-fe-ionic-opendevstack-master/fe-ionic-test/node_modules/@typescript-eslint/eslint-plugin/dist/index.js[0m
[0;32m    amazon-ebs: - /home/jenkins/.npm-global/lib/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js[0m
[0;32m    amazon-ebs: - /home/jenkins/.npm-global/lib/node_modules/eslint/node_modules/@eslint/eslintrc/lib/index.js[0m
[0;32m    amazon-ebs: - /home/jenkins/.npm-global/lib/node_modules/eslint/lib/cli-engine/cli-engine.js[0m
[0;32m    amazon-ebs: - /home/jenkins/.npm-global/lib/node_modules/eslint/lib/eslint/eslint.js[0m
[0;32m    amazon-ebs: - /home/jenkins/.npm-global/lib/node_modules/eslint/lib/eslint/index.js[0m
[0;32m    amazon-ebs: - /home/jenkins/.npm-global/lib/node_modules/eslint/lib/cli.js[0m
[0;32m    amazon-ebs: - /home/jenkins/.npm-global/lib/node_modules/eslint/bin/eslint.js[0m
[0;32m    amazon-ebs: Referenced from: /tmp/workspace/unitt-cd/unitt-cd-prov-fe-ionic-opendevstack-master/fe-ionic-test/.eslintrc.json[0m
[0;32m    amazon-ebs:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)[0m
[0;32m    amazon-ebs:     at Function.Module._load (internal/modules/cjs/loader.js:667:27)[0m
```
